#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_vmem=4G
#$ -l h_rt=24:0:0

# Load the application module
module load gatk/4.0.8.1

gatk GatherVcfs -I vcf.list -O ./single_file/Qrobur.vcf.gz

# Generated by Job Script Builder on 2018-11-05
# For assistance, please email its-research-support@qmul.ac.uk
