#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_vmem=4G
#$ -l h_rt=48:0:0

# Load the application module
module load bwa/0.7.17

bwa index -a bwtsw Qrob_PM1N.fa

# Generated by Job Script Builder on 2018-11-20
# For assistance, please email its-research-support@qmul.ac.uk
