#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 4
#$ -l h_vmem=1G
#$ -l h_rt=240:0:0
#$ -t 1-130


INPUT=$(sed -n "${SGE_TASK_ID}p" list1.txt)
OUTPUT=$(sed -n "${SGE_TASK_ID}p" list2.txt)

# Load the application module
module load samtools

samtools sort -@ 4 -m 900M -n -o /data/SBCS-BuggsLab/GabrieleNocchi/Oak/batch_2_30_samples/duplicates_removal/$OUTPUT\.bam $INPUT

# Generated by Job Script Builder on 2018-10-26
# For assistance, please email its-research-support@qmul.ac.uk

