#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_vmem=1G
#$ -l h_rt=1:0:0

# Load the application module


egrep -v "^#" Qrob_Chr01.vcf | cut -f 8 | sed 's/^.*;FS=\([0-9]*.[0-9]*\);.*$/\1/' > FS.txt


# Generated by Job Script Builder on 2018-11-13
# For assistance, please email its-research-support@qmul.ac.uk
