#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_vmem=1G
#$ -l h_rt=1:0:0

# Load the application module
module load vcftools
vcf-stats Qrob_Chr01.vcf > stats.txt

# Generated by Job Script Builder on 2018-11-13
# For assistance, please email its-research-support@qmul.ac.uk
