#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 4
#$ -l h_vmem=1G
#$ -l h_rt=70:0:0

# Load the application module
module load bcftools

bcftools annotate --set-id +'%CHROM\_%POS\_%REF\_%FIRST_ALT' 432.vcf.gz --threads 4 -Oz -o Qrobur_432_IDS.vcf.gz

# Generated by Job Script Builder on 2018-11-05
# For assistance, please email its-research-support@qmul.ac.uk
