#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_vmem=4G
#$ -l h_rt=24:0:0
#$ -t 1-13

CHROM=$(sed -n "${SGE_TASK_ID}p" ./vcf.txt)
NAME=$(sed -n "${SGE_TASK_ID}p" ./vcf_names.txt)

# Load the application module
module load gatk/4.0.8.1

gatk VariantFiltration -R /data/SBCS-BuggsLab/GabrieleNocchi/haplotypecaller_ref/Qrob_PM1N.fa -V $CHROM --filter-expression "QD < 2.0 || FS > 60.0 || MQ < 50.0 || MQRankSum < -2.0 || ReadPosRankSum < -2.0" --filter-name "SNP_filter" --missing-values-evaluate-as-failing -O ./flagged/$NAME\_filtered.vcf


rm $CHROM
# Generated by Job Script Builder on 2018-11-05
# For assistance, please email its-research-support@qmul.ac.uk

